### ISSUE TITLE
Unable to Correctly Render Colored Text in Ghost

### ISSUE THREAD

**Issue by imseanpan** [TryGhost/Koenig#1386] opened 2024-11-01 11:06 UTC
#### Description

I am trying to extend the Ghost editor by adding a button that allows setting text color. However, I found that this functionality does not work as expected.

Specifically, when I set the text color and save the post, the `lexical` field correctly records the `<span>` tags with the `style` attribute, but the `html` and `plaintext` fields have the `<span>` tags with color removed.

#### Steps to Reproduce

1. Select some text in the editor.
2. Click the color button I added and set the text color (e.g., red).
3. Save the post.
4. Check the fields in the database and observe that the `lexical` field correctly records the `<span>` tags with the `style` attribute, whereas the `html` and `plaintext` fields have the `<span>` tags with the color removed.

#### Expected Behavior

After saving the post, the `html` and `plaintext` fields should retain the `<span>` tags with color styles, and the colored text should render correctly on the front end.

#### Actual Behavior

After saving the post, the `html` and `plaintext` fields have the `<span>` tags with color styles removed.

#### Additional Notes

I would appreciate any guidance on how to retain the color styles in the `html` and `plaintext` fields, ensuring that the colored text is rendered correctly just like in the `lexical` field.

**Comment by kevinansfield** [comment] 2024-11-05 09:27
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/21496

**Closed by kevinansfield** 2024-11-05 09:27 UTC
